document.addEventListener('DOMContentLoaded', () => {
  NyayaSahay.initApp('reports', 'Reports', [
    { label: 'Home', href: 'dashboard.html' },
    { label: 'Reports' }
  ]);

  const iconSets = [
    { id: 'page-icon', icon: 'reports' },
    { id: 'icon-case-report', icon: 'cases' },
    { id: 'icon-doc-report', icon: 'documents' },
    { id: 'icon-activity-report', icon: 'clock' },
    { id: 'icon-integrity-report', icon: 'shield' },
    { id: 'icon-pdf-export', icon: 'download' },
    { id: 'icon-csv-export', icon: 'download' }
  ];

  iconSets.forEach(item => {
    const el = document.getElementById(item.id);
    if (el && NyayaSahay.icons[item.icon]) {
      el.innerHTML = NyayaSahay.icons[item.icon];
    }
  });

  const reportPreviewContent = document.getElementById('report-preview-content');

  const reportCards = document.querySelectorAll('.report-card');
  reportCards.forEach(card => {
    card.addEventListener('click', () => {
      reportCards.forEach(c => c.classList.remove('active'));
      card.classList.add('active');
      renderReportPreview(card.dataset.report);
    });
  });

  document.getElementById('btn-generate').addEventListener('click', () => {
    NyayaSahay.showToast('Report generated successfully', 'success');
  });

  document.getElementById('btn-export-pdf').addEventListener('click', () => {
    NyayaSahay.showToast('Exported to PDF successfully', 'success');
  });

  document.getElementById('btn-export-csv').addEventListener('click', () => {
    NyayaSahay.showToast('Exported to CSV successfully', 'success');
  });

  function renderReportPreview(type) {
    let dateStr = NyayaSahay.formatDate(new Date().toISOString());
    let html = '';

    if (type === 'case') {
      html = `
        <div class="report-content">
          <h2 class="mb-4">Case Status Report &mdash; September 2026</h2>
          <p class="text-muted mb-4">Generated on ${dateStr} by ${MockData.currentUser.name}</p>
          
          <h3 class="mb-2">Summary</h3>
          <div class="grid grid-2 gap-4 mb-4">
            <div class="summary-row flex justify-between border-b pb-2">
              <span>Total Active Cases</span>
              <span class="font-bold">3</span>
            </div>
            <div class="summary-row flex justify-between border-b pb-2">
              <span>Cases Under Investigation</span>
              <span class="font-bold">1</span>
            </div>
            <div class="summary-row flex justify-between border-b pb-2">
              <span>Pending Cases</span>
              <span class="font-bold">1</span>
            </div>
            <div class="summary-row flex justify-between border-b pb-2">
              <span>Closed Cases</span>
              <span class="font-bold">1</span>
            </div>
            <div class="summary-row flex justify-between border-b pb-2">
              <span>Total Documents</span>
              <span class="font-bold">10</span>
            </div>
            <div class="summary-row flex justify-between border-b pb-2">
              <span>Documents with Integrity Issues</span>
              <span class="font-bold text-danger">1</span>
            </div>
            <div class="summary-row flex justify-between border-b pb-2">
              <span>Upcoming Court Hearings</span>
              <span class="font-bold">3</span>
            </div>
            <div class="summary-row flex justify-between border-b pb-2">
              <span>Overdue Actions</span>
              <span class="font-bold">0</span>
            </div>
          </div>

          <h3 class="mb-2">Case Breakdown</h3>
          <div class="table-container mb-4">
            <table class="data-table w-full text-left">
              <thead>
                <tr>
                  <th class="p-2 border-b">Case ID</th>
                  <th class="p-2 border-b">Title</th>
                  <th class="p-2 border-b">Type</th>
                  <th class="p-2 border-b">Status</th>
                </tr>
              </thead>
              <tbody>
                ${MockData.cases.map(c => `
                  <tr>
                    <td class="p-2 border-b">${c.id}</td>
                    <td class="p-2 border-b">${c.title}</td>
                    <td class="p-2 border-b">${c.type}</td>
                    <td class="p-2 border-b">${NyayaSahay.statusBadge(c.status)}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </div>

          <div class="divider mb-4"></div>
          <p class="text-sm text-muted">This report was auto-generated by NYAYA-SAHAY on ${dateStr}. For official records, please verify with the case management office.</p>
        </div>
      `;
    } else {
      html = `
        <div class="report-content">
          <h2 class="mb-4">${type.charAt(0).toUpperCase() + type.slice(1)} Report &mdash; September 2026</h2>
          <p class="text-muted mb-4">Generated on ${dateStr} by ${MockData.currentUser.name}</p>
          <div class="empty-state p-4 text-center">
            <p>Preview data for ${type} report is currently simulated. Click Generate Report to process actual data.</p>
          </div>
          <div class="divider mb-4 mt-4"></div>
          <p class="text-sm text-muted">This report was auto-generated by NYAYA-SAHAY on ${dateStr}.</p>
        </div>
      `;
    }

    reportPreviewContent.innerHTML = html;
  }

  renderReportPreview('case');
});
